baseURL = "https://isaisi9.github.io/Website/"     # Enlace a la entrada
languageCode = "en-es"  			# Idioma
title = "TECNOLOGIAS WEB"  			# Titulo
publishDir = "docs"   				# Creacion de archivos
theme = "ananke"     				# Ruta al tema
